print("#######################################################################")
print("# Nama Lengkap   : Nur Wahid                                          #")
print("# NPM            : 5170411146                                         #")
print("# Alamat Lengkap : JL. A. YANI, RT 04, RW 02 Kel Kp. Jawa, Curup      #")
print("#######################################################################")
